name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2  # Checkout the code from the repository

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10-slim'  # Use python:3.10-slim (or change to the version your project uses)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install project dependencies

    - name: Run tests
      run: |
        pytest  # Run tests using pytest (change if you use another test framework)

    - name: Build Docker image
      run: |
        docker build -t myapp:latest .  # Build the Docker image

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker username from GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker password from GitHub Secrets

    - name: Push Docker image to DockerHub
      run: |
        docker push myapp:latest  # Push the Docker image to DockerHub (or use another registry)

    - name: Deploy using Ansible
      run: |
        ansible-playbook -i inventory/production deploy.yml  # Run your Ansible playbook for deployment
