---
- name: Deploy Todo App
  hosts: web
  become: yes  # Use sudo if necessary for installing dependencies

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    - name: Install required packages (docker and dependencies)
      apt:
        name:
          - docker.io
          - python3
          - python3-pip
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Pull latest Docker image
      docker_image:
        name: python:3.8
        tag: latest
        source: pull
      environment:
        DOCKER_HOST: "unix:///var/run/docker.sock"

    - name: Start the Docker container
      docker_container:
        name: todo-app
        image: myapp:latest
        state: started
        restart_policy: always
        ports:
          - "5200:8000"  # Map the app's internal port to the external port
        env:
          DJANGO_SETTINGS_MODULE: todoapi.settings.production  # Add any required environment variables
