---
- name: Deploy Todo App
  hosts: web
  become: yes  # Use sudo if necessary
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies (docker, python)
      apt:
        name:
          - docker.io
          - python3
          - python3-pip
        state: present

    - name: Pull latest Docker image
      docker_image:
        name: myapp
        source: pull
        tag: latest

    - name: Start the Docker container
      docker_container:
        name: todo-app
        image: myapp:latest
        state: started
        restart_policy: always
        ports:
          - "5200:8000"  # Map the ports for the app
