---
- name: Deploy Todo App
  hosts: web
  become: yes

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes

    - name: Install required packages (docker and dependencies)
      apt:
        name:
          - docker.io
          - python3
          - python3-pip
          - jq
          - curl
        state: present

    - name: Get latest Docker Compose version
      shell: curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name
      register: docker_compose_version
      changed_when: false

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version.stdout }}/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      # Add this to prevent issues with dynamic version fetching
      ignore_errors: no
